# Generated by Django 5.2.1 on 2025-05-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='pelGenero',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='pelGenero',
            field=models.ManyToManyField(blank=True, null=True, to='appPeliculas.genero'),
        ),
    ]
